[package]
name = "beofetch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.83"
hapi = { git = "https://github.com/HoneyOS-Foundation/Hapi", features = [
    "logger",
] }
